config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  get 'users/edit'

  root 'sessions#index'
  get '/login', to: "sessions#login", as: 'login'
  get '/signup', to: "sessions#signup", as: 'signup'
  post '/login', to: "sessions#attempt_login"
  post '/signup', to: "sessions#create"
  get '/home', to: "sessions#index", as: 'home'
  delete '/logout', to: "sessions#logout", as: "logout"

  resources :resets, only: [:new, :edit, :create, :update]

  get '/teams', to: "teams#all", as: "all_teams"

  resources :users do
    resources :teams, shallow: true
  end

  resources :superheros

end

app/controllers/resets_controller.rb
class ResetsController < ActionController::Base

 def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      user.generate_password_reset_token!
      Reset.password_reset(user).deliver_now
      redirect_to login_path, notice: "Email sent"
    else
      flash.now[:alert] = "Email not found"
      render :new
    end
  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])
    if @user
      # feels like we are missing something here
      # but, have no fear, we are just going to render edit.html.erb
    else
      redirect_to login_path, alert: "Invalid reset token"
    end
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])
    if params[:user][:password].present?
      if @user && @user.update(user_params)
        @user.update(password_reset_token: nil)
        session[:user_id] = @user.id
        redirect_to users_path, flash: {success: "Password updated."}
      else
        flash.now[:notice] = "Password reset token not found."
        render :edit
      end
    else
      flash.now[:alert] = "Please enter a password"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:password)
  end

end

app/views/resets/new.html.erb
<h1>Reset password</h1>
<% flash.each do |key, value| %>
      <% if key == "notice" %>
        <%= content_tag :div, value, class: "text-center alert alert-warning" %>
      <% elsif key == "alert" %>
        <%= content_tag :div, value, class: "text-center alert alert-danger" %>
      <% else %>
        <%= content_tag :div, value, class: "text-center alert alert-success" %>
      <% end %>
    <% end %>
<%= form_tag resets_path do%>
<%= label_tag :email, "Email"%>
<%= text_field_tag :email%>

<%= submit_tag "Reset Password" %>

<% end %>